import java.util.Random;

import java.util.*;

public class MonopolySimulation 
{
  
public static void main (String[]args) 
  {
    
Random rand = new Random ();
    
Scanner in = new Scanner (System.in);
    
int a[] = new int[40];	//Initialising an Array of size 40 representing each position in the monopoly board
    for (int i = 0; i < 40; i++)	//Setting the value of all elements in the array as 0
      {
	
a[i] = 0;
      
} 
int dicerolls;
    
System.out.println ("Enter number of dicerolls");
    
dicerolls = in.nextInt ();
    
int position = 0;
    
for (int i = 1; i <= dicerolls; i++)	//Entering into the loop simulating the whole game
      {
	
 
int diceone = rand.nextInt (6) + 1;	//Rolling Dice one
	int dicetwo = rand.nextInt (6) + 1;	//Rolling Dice two
	position = position + diceone + dicetwo;	//The position is changing based on what you got on the dice
	if (position == 30)	//If the position is Go to Jail i.e 30th position then the position changes to Jail
	  {
	    
position = 10;
	  
}
	
if (position == 2 || position == 17 || position == 33)	//If Position is Community Chest i.e the 2nd position or 17th position or the 33rd position
	  {
	    
int rando = rand.nextInt (17);	// Initialising a random value from 0 to 16 representing each Community Chest Card (Only 2 of the cards is for changing the position therefore only those will be taken into consideration)
	    if (rando == 0)	//Advance to GO Card
	      {
		
position = 0;
	      
}
	    
if (rando == 1)	//Go to Jail Card
	      {
		
position = 10;
	      
}
	  
}
	
if (position == 7 || position == 22 || position == 36)	//If Position is Chance i.e the 7th position or 22nd position or the 36th position
	  {
	    
int rando = rand.nextInt (16);	// Initialising a random value from 0 to 15 representing each Chance Card (Only 9 of the cards is for changing the position therefore only those will be taken into consideration)
	    if (rando == 0)	//I'm too lazy to write the comments for the rest of the chance cards
	      {
		
position = 0;
	      
}
	    
if (rando == 1)
	      
	      {
		
position = 24;
	      
}
	    
if (rando == 2)
	      
	      {
		
position = 11;
	      
}
	    
if (rando == 3)
	      
	      {
		
position = 0;
	      
}
	    
if (rando == 4)
	      
	      {
		
if (position == 7)
		  
		  {
		    
position = 12;
		  
}
		
if (position == 22)
		  
		  {
		    
position = 28;
		  
}
		
if (position == 36)
		  
		  {
		    
position = 12;
		  
}
	      
}
	    
if (rando == 5)
	      
	      {
		
if (position == 7)
		  
		  {
		    
position = 15;
		  
}
		
if (position == 22)
		  
		  {
		    
position = 25;
		  
}
		
if (position == 36)
		  
		  {
		    
position = 5;
		  
}
	      
}
	    
if (rando == 6)
	      
	      {
		
position = position - 3;
	      
}
	    
if (rando == 7)
	      
	      {
		
position = 10;
	      
}
	    
if (rando == 8)
	      
	      {
		
position = 5;
	      
}
	    
if (rando == 9)
	      
	      {
		
position = 39;
	      
}
	  
}
	
if (i % 217 == 0)	//There is a 0.46% Probability of rolling doubles thrice therefore once every 217 rolls you'll go to jail
	  {
	    
position = 10;
	  
}
	
 
 
 
 
 
if (position >= 40)	// If position increases to something like 42 then it reverts back to 2 i.e if its above 40 then it reduces back
	  {
	    
position = position - 40;
	  
}
	
a[position] = a[position] + 1;	//Every time it lands in a specific position then the corresponding array element representing the position increments by one
      }
    
 
 
 
System. 
      out.println ("Aggregate probability of Landing on Orange in a game: " +
		   
(double) (a[16] + a[18] + a[19]) / dicerolls * 100 + "%");
    
System. 
 out.
      println ("Aggregate probability of Landing on Red in a game: " +
	       
(double) (a[21] + a[23] + a[24]) / dicerolls * 100 + "%");
    
System. 
 out.
      println ("Aggregate probability of Landing on RailRoad in a game: " 
	       +(double) (a[5] + a[15] + a[25] + 
a[35]) / dicerolls * 100 +
	       "%");
    
System. 
 out.
      println ("Aggregate probability of Landing on LightBlue in a game: " 
	       +(double) (a[6] + a[8] + a[9]) / dicerolls * 100 + "%");
    
System. 
 out.
      println ("Aggregate probability of Landing on Pink in a game: " +
	       
(double) (a[11] + a[13] + a[14]) / dicerolls * 100 + "%");
    
System. 
 out.
      println ("Aggregate probability of Landing on Green in a game: " +
	       
(double) (a[31] + a[32] + a[34]) / dicerolls * 100 + "%");
    
System. 
 out.
      println ("Aggregate probability of Landing on DarkBlue in a game: " 
	       +(double) (a[37] + a[39]) / dicerolls * 100 + "%");
    
System. 
 out.
      println ("Aggregate probability of Landing on Brown in a game: " +
	       
(double) (a[1] + a[3]) / dicerolls * 100 + "%");
    
System. 
 out.
      println ("Aggregate probability of Landing on Yellow in a game: " +
	       
(double) (a[26] + a[27] + a[29]) / dicerolls * 100 + "%");
    
System.out.
      println
      ("The individual probabilites of each position are:    (GO is position 0)");
    
 
for (int j = 0; j < 40; j++)
      
      {
	
 
System.out.println (j + ")" + ((double) a[j]) / dicerolls * 100 +
			       
"%");

} 
 
 
 
 
 
 
 
 
 
 
 
 
} 
}
